apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "druid.component.name" (list "historical" .) }}
  labels:
    {{- include "druid.component.labels" (list "historical" .) | indent 4 }}
  annotations:
    {{- include "druid.component.annotations" (list "historical" .) | indent 4 }}
spec:
  serviceName: {{ include "druid.component.name" (list "historical" .) }}
  replicas: {{ .Values.historical.replicas }}
  selector:
    matchLabels:
      {{- include "druid.component.match.labels" (list "historical" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "druid.component.labels" (list "historical" .) | indent 8 }}
        {{- include "druid.component.match.labels" (list "historical" .) | nindent 8 }}
      annotations:
        {{- include "druid.component.annotations" (list "historical" .) | indent 8 }}
    spec:
      {{- include "common.security" . | nindent 6 }}
      nodeSelector:
        {{- include "druid.component.node.selector" (list "historical" .) | nindent 8 }}
      volumes:
        {{- include "druid.component.volumes" (list "historical" .) | nindent 8 }}
      containers:
        - name: {{ include "druid.component.name" (list "historical" .) }}
          {{- include "druid.image" . | nindent 10 }}
          args: ["historical"]
          {{- include "druid.ports" (list "historical" 8283) | nindent 10 }}
          env:
            {{- include "common.env" . | nindent 12 }}
          resources:
            {{- toYaml .Values.historical.resources | nindent 12 }}
          volumeMounts:
            {{- include "druid.component.volumeMounts" (list "historical" .) | nindent 12 }}
          {{- include "druid.probes" (list 8283 "/status/health" "/druid/historical/v1/readiness") | nindent 10 }}
