apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "druid.name" . }}-druid-metadata
  labels:
    {{- include "common.labels" . | indent 4 }}
  annotations:
    {{- include "common.annotations" . | indent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ include "druid.name" . }}-druid-metadata
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ include "druid.name" . }}-druid-metadata
        property: username
    - secretKey: password
      remoteRef:
        key: {{ include "druid.name" . }}-druid-metadata
        property: password
    - secretKey: host
      remoteRef:
        key: {{ include "druid.name" . }}-druid-metadata
        property: host
    - secretKey: dbname
      remoteRef:
        key: {{ include "druid.name" . }}-druid-metadata
        property: dbname
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "druid.name" . }}-druid-admin
  labels:
    {{- include "common.labels" . | indent 4 }}
  annotations:
    {{- include "common.annotations" . | indent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ include "druid.name" . }}-druid-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ include "druid.name" . }}-druid-admin
        property: username
    - secretKey: password
      remoteRef:
        key: {{ include "druid.name" . }}-druid-admin
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "druid.name" . }}-druid-system
  labels:
    {{- include "common.labels" . | indent 4 }}
  annotations:
    {{- include "common.annotations" . | indent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ include "druid.name" . }}-druid-system
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ include "druid.name" . }}-druid-system
        property: username
    - secretKey: password
      remoteRef:
        key: {{ include "druid.name" . }}-druid-system
        property: password
