apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "druid.name" . }}-druid-sa
  labels:
    {{- include "common.labels" . | indent 4 }}
  annotations:
    {{- include "common.annotations" . | indent 4 }}
