apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "druid.component.name" (list "overlord" .) }}-conf
  labels:
    {{- include "druid.component.labels" (list "overlord" .) | indent 4 }}
  annotations:
    {{- include "druid.component.annotations" (list "overlord" .) | indent 4 }}
data:
  "log4j2.xml":
    {{- .Files.Get "common/log4j2.xml" | toYaml | indent 4 }}
  "jvm.config":
    {{- include "druid.component.jvm" (list "overlord" .) | indent 4 }}
  "runtime.properties":
    {{- .Values.overlord.runtime | toYaml | indent 4 }}
